# Initial AUTO value, it will get updated accordingly
AUTO: True
# Location's lat and lon
LON: 51.5
LAT: -0.116
# number of all possible servo channels
ALL_CHANNELS: 16

# integer denotes the channel for the servo
1:
  # Current status of the blind 0 is completely up, 1 is completely down. Required.
  STATUS: 0.0
  # If positive, delay in minutes on the blind sunrise operation. If negative, brings the blind sunrise operation by x
  # time in minutes. Will default to 0.
  SERVO_DETAILS:
    stationary_degrees: 92
    open_time: sensor
    close_time: 95
    open_degrees: 90
    close_degrees: 94
  SENSOR_DETAILS:
    open:
      # to be read from the sensor, the value is the boundary defining whether the blind is open
      proximity: 15
  SUNRISE_BUFFER: 60
  # If positive, delay in minutes on the blind sunset operation. If negative, brings the blind sunset operation by x
  # time in minutes. Will default to 0.
  SUNSET_BUFFER: -60

