# Initial AUTO value, it will get updated accordingly
AUTO: True
# In minutes, how often to check for changes to config. Will default to 10. Blind opening/closing with `BUFFER` delay
# will be accurate up this value
UPDATE_FREQUENCY: 10
# number of all possible servo channels
ALL_CHANNELS: 16

# integer denotes the channel for the servo
1:
  # Current status of the blind 0 is completely up, 1 is completely down. Required.
  STATUS: 0.0
  # If positive, delay in minutes on the blind sunrise operation. If negative, brings the blind sunrise operation by x
  # time in minutes. Will default to 0.
  SUNRISE_BUFFER: 60
  # If positive, delay in minutes on the blind sunset operation. If negative, brings the blind sunset operation by x
  # time in minutes. Will default to 0.
  SUNSET_BUFFER: -60
  # Number of 180 rotations the servo has to complete to complete the job (close the blind/curtain)
  ROTATIONS_TO_CLOSE: 10

